name: 'penaestrada-server'
version: '3.9'
services:
  postgres:
    image: bitnami/postgresql:16.4.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: penaestrada_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
